### ISSUE TITLE
Regression in workspace cloning related to tags

### ISSUE THREAD

**Issue by tulir** [rage/concepts#535]
Might be something to do with new tag types (goal tags?)

**Comment by d471061c** [comment]
```
backend_1   | 2020-02-28 11:45:03 --- Code: 'NOT_FOUND',Query: 'workspaceBySourceTemplate', Message: 'Workspace not found'
backend_1   | NotFoundError: Workspace not found
backend_1   |     at workspaceBySourceTemplate (/concepts/backend/src/resolvers/Query/Workspace.js:44:11)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend_1   |     at authenticate (/concepts/backend/src/middleware/authentication.js:28:10)
backend_1   |     at async Promise.all (index 0)
backend_1   |     at async Promise.all (index 0) {
backend_1   |   message: 'Workspace not found',
backend_1   |   locations: [ { line: 2, column: 3 } ],
backend_1   |   path: [ 'workspaceBySourceTemplate' ],
backend_1   |   extensions: { type: 'workspace', id: undefined, code: 'NOT_FOUND' }
backend_1   | }
backend_1   | NotFoundError: Workspace not found
backend_1   |     at workspaceBySourceTemplate (/concepts/backend/src/resolvers/Query/Workspace.js:44:11)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend_1   |     at authenticate (/concepts/backend/src/middleware/authentication.js:28:10)
backend_1   |     at async Promise.all (index 0)
backend_1   |     at async Promise.all (index 0)
backend_1   | 2020-02-28 11:45:03 --- Mutation: 'cloneTemplateWorkspace', Message: 'No Node for the model Tag with value ck6kfbll203f4uhFBlxBC0YMz for id found.'
backend_1   | Error: No Node for the model Tag with value ck6kfbll203f4uhFBlxBC0YMz for id found.
backend_1   |     at BatchedGraphQLClient.<anonymous> (/concepts/backend/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
backend_1   |     at step (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
backend_1   |     at Object.next (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
backend_1   |     at fulfilled (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
backend_1   |   message: 'No Node for the model Tag with value ck6kfbll203f4uhFBlxBC0YMz for id found.',
backend_1   |   locations: [ { line: 2, column: 3 } ],
backend_1   |   path: [ 'cloneTemplateWorkspace' ]
backend_1   | }
backend_1   | Error: No Node for the model Tag with value ck6kfbll203f4uhFBlxBC0YMz for id found.
backend_1   |     at BatchedGraphQLClient.<anonymous> (/concepts/backend/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
backend_1   |     at step (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
backend_1   |     at Object.next (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
backend_1   |     at fulfilled (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend_1   | 2020-02-28 11:45:09 --- Mutation: 'cloneTemplateWorkspace', Message: 'No Node for the model Tag with value ck6kfbll203f4kg3hknUJMjm5 for id found.'
backend_1   | Error: No Node for the model Tag with value ck6kfbll203f4kg3hknUJMjm5 for id found.
backend_1   |     at BatchedGraphQLClient.<anonymous> (/concepts/backend/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
backend_1   |     at step (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
backend_1   |     at Object.next (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
backend_1   |     at fulfilled (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
backend_1   |   message: 'No Node for the model Tag with value ck6kfbll203f4kg3hknUJMjm5 for id found.',
backend_1   |   locations: [ { line: 2, column: 3 } ],
backend_1   |   path: [ 'cloneTemplateWorkspace' ]
backend_1   | }
backend_1   | Error: No Node for the model Tag with value ck6kfbll203f4kg3hknUJMjm5 for id found.
backend_1   |     at BatchedGraphQLClient.<anonymous> (/concepts/backend/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
backend_1   |     at step (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
backend_1   |     at Object.next (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
backend_1   |     at fulfilled (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
backend_1   | 2020-02-28 12:21:04 --- Mutation: 'cloneTemplateWorkspace', Message: 'No Node for the model Tag with value ck6kfbll203f4gbYBApVoe8Vr for id found.'
backend_1   | Error: No Node for the model Tag with value ck6kfbll203f4gbYBApVoe8Vr for id found.
backend_1   |     at BatchedGraphQLClient.<anonymous> (/concepts/backend/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
backend_1   |     at step (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
backend_1   |     at Object.next (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
backend_1   |     at fulfilled (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
backend_1   |   message: 'No Node for the model Tag with value ck6kfbll203f4gbYBApVoe8Vr for id found.',
backend_1   |   locations: [ { line: 2, column: 3 } ],
backend_1   |   path: [ 'cloneTemplateWorkspace' ]
backend_1   | }
backend_1   | Error: No Node for the model Tag with value ck6kfbll203f4gbYBApVoe8Vr for id found.
backend_1   |     at BatchedGraphQLClient.<anonymous> (/concepts/backend/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
backend_1   |     at step (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
backend_1   |     at Object.next (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
backend_1   |     at fulfilled (/concepts/backend/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
backend_1   |     at runMicrotasks (<anonymous>)
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
